name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types:
      - created

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Retrieve version from release tag name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Display release version
        run: echo ${{ env.RELEASE_VERSION }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/bin
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install trunk
        run: cargo install --locked trunk || true
      - name: Install wasm-bindgen-cli
        run: cargo install --locked wasm-bindgen-cli || true
      - name: Add wasm32-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown || true
      - name: Build application binary
        run: .scripts/ci_app
